modified:   bin/controller 	new file:   bin/log-daemon 	modified:   bin/log-streama 	new file:   bin/start-daemon 	modified:   bin/start-streama 	new file:   bin/stop-daemon 	modified:   bin/stop-streama 	new file:   program 	deleted:    streama-daemon

diff --git a/bin/controller b/bin/controller
--- a/bin/controller
+++ b/bin/controller
@@ -3,9 +3,6 @@
 # Version: 1.0.1
 # Website: https://www.doonline.nl
 
-# Save the daemon's pid so it can be killed later.
-echo $! > '/usr/local/lib/streama/etc/daemon.pid';
-
 # Start streama.
 echo -e "[streama-daemon] Starting streama... This would usually take around 3 minutes." >> '/usr/local/lib/streama/etc/daemon.log';
 bash /usr/local/lib/streama/bin/start-streama;
@@ -28,7 +25,7 @@ while read _RUN _FOR _STEP do
 		$(( _RUN + "$STEP" ));
 	else	
 		# Restart streama and log it to etc/streama.log and append that log to etc/last.log.
-		bash /usr/local/lib/streama/bin/stop-streama && \
+		bash /usr/local/lib/streama/bin/stop-streama || echo -e "[streama-daemon] ERROR: Couldn't stop streama... Shutting down this daemon and trying again one more time!" >> '/usr/local/lib/streama/etc/daemon.log' && exit;
 		sleep "$_STEP" && \
 		echo -e "[streama-daemon] Restarting streama... This would usually take around 3 minutes." >> '/usr/local/lib/streama/etc/daemon.log' && \
 		sleep "$_STEP" && \
@@ -53,5 +50,10 @@ $IFS=$_OLD_IFS;
 # Stop streama and check if it was executed correctly, then exit.
 bash /usr/local/lib/streama/bin/stop-streama;
 _RESULT=$?;
+
+# Empty var file for next run.
+echo -e "" > '/usr/local/lib/streama/etc/daemon.var';
+
+# Exiting the daemon process
 [ $_RESULT -ne 0 ] && echo -e "[streama-daemon] Couldn't stop streama, something went wrong getting streama's pid." >> '/usr/local/lib/streama/etc/daemon.log' && exit 1;
 [ $_RESULT -eq 0 ] && echo -e "[streama-daemon] Stopped streama, everything should be gone right." >> '/usr/local/lib/streama/etc/daemon.log' && exit 0;
diff --git a/bin/start-streama b/bin/start-streama
--- a/bin/start-streama
+++ b/bin/start-streama
@@ -14,27 +14,27 @@ function _start()
 	cd '/usr/local/lib/streama/' && \
 	
 	# Let the user know the program is starting
-	echo -e "[streama-daemon] Starting background process..." && \
-	echo -e "[streama-daemon] Use 'streama stop' to stop streama's daemon." && \
-	echo -e "[streama-daemon] Use 'streama help' for more instructions." && \
+	echo -e "[streama-daemon] Starting background process..." >> '/usr/local/lib/streama/etc/daemon.log' && \
+	echo -e "[streama-daemon] Use 'streama stop' to stop streama's daemon." >> '/usr/local/lib/streama/etc/daemon.log' && \
+	echo -e "[streama-daemon] Use 'streama help' for more instructions." >> '/usr/local/lib/streama/etc/daemon.log' && \
 	
 	# Execute jar with java and make sure it won't respond to session exits and startups and save the output of the executable to a log file.
-	nohup java -Xms128m -Xmx"$_max_memory" -Xnoclassgc -Dgrails.env="$_load_env" -Dserver.port="$_local_port" -jar '/usr/local/lib/streama/streama.jar' > '/usr/local/lib/streama/etc/streama.log' 2>&1 &
+	nohup java -Xms128m -Xmx"$_max_memory" -Xnoclassgc -Dgrails.env="$_load_env" -Dserver.port="$_local_port" -jar '/usr/local/lib/streama/bin/streama.jar' > '/usr/local/lib/streama/etc/streama.log' 2>&1 &
 
 	# Save the pid of this program to a file for later use in for example: shutdown of the program.
-	echo $! > '/usr/local/lib/streama/etc/streama.pid' && \
-	echo -e "[streama-daemon] Successfully started background process with pid: $!..." && \
-	echo -e "[streama-daemon] Use 'streama read {process/daemon}' to see live streama's logs in the terminal.";
+	echo $! > '/usr/local/lib/streama/etc/streama.pid' >> '/usr/local/lib/streama/etc/daemon.log' && \
+	echo -e "[streama-daemon] Successfully started background process with pid: $!..." >> '/usr/local/lib/streama/etc/daemon.log' && \
+	echo -e "[streama-daemon] Use 'streama read {process/daemon}' to see live streama's logs in the terminal." >> '/usr/local/lib/streama/etc/daemon.log';
 
 	# Return results for checking if execution went right.
-	return $?;
+	return 0;
 }
 
 # Execute start function.
 _start production 512m 8080;
 
 # Check for errors during execution.
-[ $? -ne 0 ] && echo -e "[streama-daemon] ERROR: Streama could not be started, please read the manual." > "/usr/local/lib/streama/etc/streama.log" && exit 1;
+[ $? -ne 0 ] && echo -e "[streama-daemon] ERROR: Streama could not be started, please read the manual." >> '/usr/local/lib/streama/etc/daemon.log' && exit 1;
 
 # Exit this bash script.
 exit 0;
